apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
  labels:
    app: library-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
        - name: library-app
          image: ghcr.io/hasekon/library-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: library-config
            - secretRef:
                name: library-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/books
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/books
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
