apiVersion: v1
kind: Secret
metadata:
  name: library-secrets
type: Opaque
stringData:
  APP_KEY: "base64:EnnCvzCUJN5Sg05fSPX+rWFpomB8tEVJBcqQJM1OvXY="
  DB_USERNAME: "library_user"
  DB_PASSWORD: "secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootsecret"
  MYSQL_DATABASE: "library"
  MYSQL_USER: "library_user"
  MYSQL_PASSWORD: "secret"
